### ISSUE TITLE
Slides showing interaction between two remote machines are broken

### ISSUE THREAD

**Issue by illia-bobyr** [nomeata/codeworld-talk#2]
Seems like slides that are supposed to show how computers change don't seem to work.
Or is there a key that is needed to start the animation?

Also, it would be great to add all the other keys in the readme:

"O" to split slides into two player mode (or is there a better way to call this?).
"="/"-" to increase/decrease simulated network delay.

**Comment by nomeata** [comment]
Some animations start paused, and you have to press `P`.
